In [9]:
import seaborn as sns

In [10]:
df = sns.load_dataset('titanic')

In [11]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
df = df[['survived' ,'pclass', 'sex' , 'age' , 'fare' , 'embarked']]

In [13]:
df.head()

   survived  pclass     sex   age     fare embarked
0         0       3    male  22.0   7.2500        S
1         1       1  female  38.0  71.2833        C
2         1       3  female  26.0   7.9250        S
3         1       1  female  35.0  53.1000        S
4         0       3    male  35.0   8.0500        S

In [14]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
fare          0
embarked      2
dtype: int64

In [15]:
df.shape

(891, 6)

In [16]:
df.dropna(inplace = True)

In [17]:
df.shape

(712, 6)

In [19]:
from sklearn.preprocessing import LabelEncoder , StandardScaler

In [20]:
lb = LabelEncoder()

In [21]:
df['sex'] = lb.fit_transform(df['sex'])
df['embarked'] = lb.fit_transform(df['embarked'])

In [23]:
x = df.drop('survived' , axis = 1)
y = df['survived']

In [25]:
sc = StandardScaler()

In [26]:
x_scaled = sc.fit_transform(x)

In [27]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(x_scaled , y , test_size = 0.2 , random_state = 42)

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [40]:
clf = KNeighborsClassifier(n_neighbors=7)

In [41]:
clf.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=7)

In [42]:
clf.score(X_test , y_test)

0.8111888111888111